version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - run:
          name: Install Dependencies
          command: |
            apk add --update git patch curl
            apk add --update ca-certificates openssl && update-ca-certificates
            apk add jq
            tlmgr update --self
            tlmgr install ulem german stmaryrd
      - checkout
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          name: Generating current version
          command: |
            latexmk Lineare_Algebra.tex;
            mkdir /tmp/artifacts;
            cp Lineare_Algebra.pdf /tmp/artifacts/
      - run:
          name: Publish to Releases
          command: |
            VERSION=$CIRCLE_BUILD_NUM
            API_JSON=$(printf '{"tag_name": "v%s","target_commitish": "master","name": "v%s","body": "Another Build %s","draft": false,"prerelease": false}' $VERSION $VERSION $VERSION)
            UPLOAD_URL=$(curl --data "$API_JSON" https://api.github.com/repos/vale981/LAAG1/releases?access_token=a4a8a9ce756374d3aa9772a33d96a4d0f6057fd4 )
            echo $UPLOAD_URL
            curl -H "Authorization: a4a8a9ce756374d3aa9772a33d96a4d0f6057fd4" -H "Accept: application/vnd.github.manifold-preview" -H "Content-Type: application/pdf" --data-binary /tmp/artifacts/Lineare_Algebra.pdf $UPLOAD_URL?name=Lineare_Algebra.pdf

      - store_artifacts:
          path: /tmp/artifacts
