version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja
    steps:
      - checkout
      - run: cp .latexmkrc ~/.latexmkrc
      - run:
          name: Generating current version
          command: |
            latexmk Lineare_Algebra.tex;
            mkdir /tmp/artifacts;
            cp Lineare_Algebra.pdf /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
